# Generated by Django 5.0.2 on 2024-10-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
