# Generated by Django 5.0.2 on 2024-10-13 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=65),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Identity', 'Identity'), ('Address', 'Address'), ('Other', 'Other')], max_length=10)),
                ('document_path', models.FileField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to='allveg.users')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to='allveg.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='allveg.users')),
            ],
        ),
    ]
