# Generated by Django 5.0.2 on 2024-10-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0003_alter_users_full_name_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bank_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='allveg.users')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allveg.users')),
            ],
        ),
    ]
