# Generated by Django 5.0.2 on 2024-10-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0004_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralManager',
            fields=[
                ('general_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('fathers_or_husbands_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('aadhaar_number', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('residential_address', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=55)),
                ('assigned_city', models.CharField(max_length=55)),
                ('joining_date', models.DateTimeField()),
                ('employee_id', models.CharField(max_length=255, unique=True)),
                ('document_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bank_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.bankdetails')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='allveg.users')),
                ('document_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.documents')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.users')),
            ],
        ),
    ]
