# Generated by Django 5.0.2 on 2024-10-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0005_generalmanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralManager',
            new_name='GeneralManagers',
        ),
    ]
