# Generated by Django 5.0.2 on 2024-10-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0006_rename_generalmanager_generalmanagers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmanagers',
            name='document_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
