# Generated by Django 5.0.2 on 2024-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0007_alter_generalmanagers_document_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalmanagers',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='generalmanagers',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
