# Generated by Django 5.0.2 on 2024-10-13 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0009_legalcompliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmanagers',
            name='legal_compliance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.legalcompliance'),
        ),
    ]
