# Generated by Django 5.0.2 on 2024-10-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0011_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmanagers',
            name='aadhaar_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalmanagers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalmanagers',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='generalmanagers',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='managers',
            name='aadhaar_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='managers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='managers',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='managers',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
