# Generated by Django 5.0.2 on 2024-10-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0012_alter_generalmanagers_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bank_detail_id',
            new_name='bank_details_id',
        ),
        migrations.RenameField(
            model_name='bankdetails',
            old_name='created_by',
            new_name='modified_by',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('Farmer', 'Farmer'), ('AgriMember', 'AgriMember'), ('Leader', 'Leader'), ('Manager', 'Manager'), ('GeneralManager', 'GeneralManager')], max_length=20, null=True),
        ),
    ]
