# Generated by Django 5.0.2 on 2024-10-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0013_rename_bank_detail_id_bankdetails_bank_details_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user_id',
        ),
        migrations.AddField(
            model_name='documents',
            name='entity_type',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('AgriMember', 'AgriMember'), ('Leader', 'Leader'), ('Manager', 'Manager'), ('GeneralManager', 'GeneralManager')], default='Farmer', max_length=20),
        ),
        migrations.AddField(
            model_name='documents',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.users'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='entity_type',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('AgriMember', 'AgriMember'), ('Leader', 'Leader'), ('Manager', 'Manager'), ('GeneralManager', 'GeneralManager')], default='Farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('Identity', 'Identity'), ('Address', 'Address'), ('Bank', 'Bank'), ('Land', 'Land'), ('Photo', 'Photo'), ('Education', 'Education'), ('Other', 'Other')], max_length=20),
        ),
    ]
