# Generated by Django 5.0.2 on 2024-10-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0014_district_remove_documents_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='Districts',
        ),
    ]
