# Generated by Django 5.0.2 on 2024-10-16 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0015_rename_district_districts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalcompliance',
            old_name='created_by',
            new_name='modified_by',
        ),
        migrations.RemoveField(
            model_name='generalmanagers',
            name='bank_details_id',
        ),
        migrations.RemoveField(
            model_name='generalmanagers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalmanagers',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='generalmanagers',
            name='document_path',
        ),
        migrations.RemoveField(
            model_name='generalmanagers',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='legalcompliance',
            name='role',
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='address_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='bank_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='education_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='identity_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updator', to='allveg.users'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='other_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='generalmanagers',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='legalcompliance',
            name='entity_type',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('AgriMember', 'AgriMember'), ('Leader', 'Leader'), ('Manager', 'Manager'), ('GeneralManager', 'GeneralManager')], default='Farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalmanagers',
            name='legal_compliance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_compliances', to='allveg.legalcompliance'),
        ),
        migrations.DeleteModel(
            name='Managers',
        ),
    ]
