# Generated by Django 5.0.2 on 2024-10-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0017_remove_generalmanagers_other_doc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmanagers',
            name='bank_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='allveg.bankdetails'),
        ),
    ]
