# Generated by Django 5.0.2 on 2024-10-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0019_rename_created_by_users_modified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taluks',
            fields=[
                ('taluk_id', models.AutoField(primary_key=True, serialize=False)),
                ('taluk_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allveg.districts')),
            ],
        ),
    ]
