# Generated by Django 5.0.2 on 2024-10-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0020_taluks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taluks',
            old_name='district',
            new_name='district_id',
        ),
    ]
