# Generated by Django 5.0.2 on 2024-10-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0021_rename_district_taluks_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalmanagers',
            name='land_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_documents', to='allveg.documents'),
        ),
    ]
