# Generated by Django 5.1.2 on 2024-10-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0023_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('leader_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('fathers_or_husbands_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('residential_address', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('assigned_area', models.CharField(max_length=100)),
                ('supervisor_manager_id', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('bank_details_id', models.IntegerField(blank=True, null=True)),
                ('identity_document_id', models.IntegerField(blank=True, null=True)),
                ('address_document_id', models.IntegerField(blank=True, null=True)),
                ('legal_compliance_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
