# Generated by Django 5.1.2 on 2024-10-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0024_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='address_document_id',
            new_name='supervisor_general_manager_id',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='identity_document_id',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='supervisor_manager_id',
        ),
        migrations.AddField(
            model_name='leader',
            name='address_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_address_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='leader',
            name='bank_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_bank_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='leader',
            name='education_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_education_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='leader',
            name='identity_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_identity_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='leader',
            name='land_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_land_documents', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='leader',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_photo_documents', to='allveg.documents'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='bank_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_bank_details', to='allveg.bankdetails'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='legal_compliance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='l_legal_compliances', to='allveg.legalcompliance'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
