# Generated by Django 5.1.2 on 2024-10-18 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0025_rename_address_document_id_leader_supervisor_general_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriMember',
            fields=[
                ('agri_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_or_husbands_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_area', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor_general_manager_id', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('address_doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_address_documents', to='allveg.documents')),
                ('bank_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_bank_details', to='allveg.bankdetails')),
                ('bank_doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_bank_documents', to='allveg.documents')),
                ('education_doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_education_documents', to='allveg.documents')),
                ('identity_doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_identity_documents', to='allveg.documents')),
                ('land_doc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_land_documents', to='allveg.documents')),
                ('legal_compliance_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_legal_compliances', to='allveg.legalcompliance')),
                ('photo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ag_photo_documents', to='allveg.documents')),
            ],
        ),
    ]
