# Generated by Django 5.1.2 on 2024-10-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0028_alter_farmer_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrimember',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.users'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.users'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allveg.users'),
        ),
    ]
