# Generated by Django 5.1.2 on 2024-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0029_alter_agrimember_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document_type',
            field=models.CharField(choices=[('Identity', 'Identity'), ('Address', 'Address'), ('Bank', 'Bank'), ('Land', 'Land'), ('Photo', 'Photo'), ('Education', 'Education'), ('Other', 'Other'), ('Business', 'Business'), ('GST', 'GST'), ('PanCard', 'PanCard')], max_length=20),
        ),
    ]
