# Generated by Django 5.1.2 on 2024-10-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0030_alter_documents_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=65)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('assigned_city', models.CharField(max_length=55)),
                ('bank_details_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_bank_details', to='allveg.bankdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_bank_details', to='allveg.users')),
            ],
        ),
    ]
