# Generated by Django 5.1.2 on 2024-10-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0031_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='assigned_city',
            new_name='address',
        ),
    ]
