# Generated by Django 5.1.2 on 2024-10-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0032_rename_assigned_city_buyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
