# Generated by Django 5.1.2 on 2024-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0034_buyer_business_id_buyer_gst_id_buyer_pancard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='business_id',
            new_name='business_doc_id',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='gst_id',
            new_name='gst_doc_id',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='pancard_id',
            new_name='pancard_doc_id',
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('Street_Vendor', 'Street_Vendor'), ('Small_Store', 'Small_Store'), ('Big_Store', 'Big_Store'), ('Canteen', 'Canteen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
