# Generated by Django 5.1.2 on 2024-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0035_rename_business_id_buyer_business_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_type',
            field=models.CharField(choices=[('Street_Vendor', 'Street_Vendor'), ('Small_Store', 'Small_Store'), ('Big_Store', 'Big_Store'), ('Canteen', 'Canteen')], default='Canteen', max_length=20),
        ),
    ]
