# Generated by Django 5.1.2 on 2024-10-22 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0037_alter_documents_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_owner_full_name', models.CharField(max_length=65)),
                ('driver_full_name', models.CharField(max_length=65)),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_number', models.CharField(max_length=25)),
                ('vehicle_registration_number', models.CharField(max_length=25)),
                ('vehicle_insurance_number', models.CharField(max_length=15)),
                ('vehicle_insurance_expiry_date', models.DateField()),
                ('driving_license_number', models.CharField(max_length=30)),
                ('driving_license_expiry_date', models.DateField()),
                ('bank_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bank_details', to='allveg.bankdetails')),
                ('driving_license_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_license_doc', to='allveg.documents')),
                ('identity_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_doc', to='allveg.documents')),
                ('pancard_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pan_doc', to='allveg.documents')),
                ('photo_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_doc', to='allveg.documents')),
                ('vehicle_insurance_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_insurance_doc', to='allveg.documents')),
                ('vehicle_rc_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_rc_book', to='allveg.documents')),
            ],
        ),
    ]
