# Generated by Django 5.1.2 on 2024-10-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allveg', '0038_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='driving_license_doc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='identity_doc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pancard_doc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='photo_doc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_insurance_doc',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_rc_book',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bank_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_bank_details', to='allveg.bankdetails'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driving_license_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_driving_license_doc_id', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='identity_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_identity_doc_id', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pancard_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_pan_doc_id', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_photo_id', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_insurance_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_vehicle_insurance', to='allveg.documents'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_rc_book_doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='v_vehicle_rc_book', to='allveg.documents'),
        ),
    ]
